#!/bin/sh
echo > /etc/torrc

for conf in $(env | awk -F "=" '{print $1}'); do [[ $(echo $conf | cut -c -6) == "TORRC_" ]] && echo "$(echo $conf | cut -c 7-) $(printenv $conf)" | tee -a /etc/torrc; done
exec "$@"
